### ISSUE TITLE
Design review: Create a list of the main functions

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-web-console#826]
A description of the most used tasks performed in the web-console. This will be used in the design-review of the web console which we will do together with the EDS team.

**Comment by Pespiri** [comment]
- [ ] split secrets into categories
- [ ] merge linked secrets (secrets are related and view/details can be displayed the same)
- [ ] customize tables for each category

**Comment by Richard87** [comment]
## Main functions:

- Create new app
- List applications I can administrate (with reader role for admin), with status
- application details:
  - list environments
  - view and edit configuration
  - Environments:
    - List components and jobs for environment
    - Start/Stop/Restart all components in environment
    - View kubernetes events for environment
    - Configure alerting
    - Components
      - View status and logs
      - Vulnerability scanning results
      - View/Configure secrets and variables 
      - Start/Stop/Restart component
    - Jobs
      - View status of job manager
      - Restart job manager
      - view configure secrets/variables
      - Vulnerability scanning results
      - List jobs and batches
      - View status jobs and batches
      - Stop, Delete and Restart jobs and batches
      - View job logs
  - Pipeline jobs
    - View status and logs
    - List pipeline jobs with status
    - View pipeline job details (steps and logs)
    - Stop / Restart pipeline job
    - Create new pipeline job
  - Configuration
    - Configure build secrets
    - Configure private container registry / Image hubs
    - Configure access control (admin and reader group)
    - Configure GitHub repository (branch / radixconfig / deploy key / webhook secret)
