### ISSUE TITLE
Implement automatic generation of API client - cost-api

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-web-console#870]
The Cost Allocation API supports the OpenAPI standard which can be used to automatically generate the API implementation.

This removes the burden of manually checking the API for changes, simplifying maintenance and reducing manual code.

- [x] Setup necessary configurations for the API generator
- [x]  Generate API
- [x]  Replace old implementations with new generated ones
- [x]  Cleanup and remove the old API implementation (where possible)

[Cost allocation api](https://github.com/equinor/radix-cost-allocation-api)
#866

**Comment by Pespiri** [comment]
The Cost Allocation API supports the OpenAPI standard which can be used to generate automatically the API implementation.

This removes the burden of manually checking the API for changes, simplifying maintenance and reducing manual code.

- [ ] Setup necessary configurations for the API generator
- [ ] Generate API
- [ ] Replace old implementations with new generated ones
- [ ] Cleanup and remove the old API implementation (where possible)

**Comment by Pespiri** [comment]
completed
