### ISSUE TITLE
Web Console crash when checking replica component logs

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-web-console#879]
Error in loading of Web Console

**Comment by Pespiri** [comment]
there seems to be two issues causing issues in the web console:

1. A sort instruction is attempted on a read-only list object. Object used to not be readonly until the change to the autogenerated apis, meaning we probably used data incorrectly in the past.
1. An error object is (probably) being used without being checked if is exists in getErrorData in the AnotherAsyncResource component
