### ISSUE TITLE
Edit component/job environment variable does not show new value after save

### ISSUE THREAD

**Issue by nilsgstrabo** [equinor/radix-web-console#884]
When we edit and save environment variables, the new value is not show after save. We have to wait for next refresh (every 15 sec) to run.

On save, Radix Web Console will do a new GET request for envvars, but it seems that this call is performed before the PATCH request is completed. The GET envvar should wait for PATCH to succeed.

**Comment by Pespiri** [comment]
this may have been solved in this PR
https://github.com/equinor/radix-web-console/pull/898

**Comment by emirgens** [comment]
Verified OK
