### ISSUE TITLE
Job component form issues with buttons and aux-pod

### ISSUE THREAD

**Issue by satr** [equinor/radix-web-console#912]
* There are two replicas, shown on the web, one is a job-scheduler, another one is aux-pod, which is not expected to be restarted. This aux-pod need to be marked properly. This pod need to be restated together with restart of main job-component.
* Job-component form can loose job-manager section and show wrong start-stop buttons, when return back from job-manager log side.

**Comment by emirgens** [comment]
Test after upgrade to new API model

**Comment by satr** [comment]
Implemented
