### ISSUE TITLE
Error on msaljs lib timeout (wait for next reported error)

### ISSUE THREAD

**Issue by satr** [equinor/radix-web-console#954]
When select Radix app admin AD Group, there can be an error, returned by msaljs lib:
_"BrowserAuthError: monitor_window_timeout: Token acquisition in iframe failed due to timeout. For more visit: aka.ms/msaljs/browser-errors"_
<img width="1012" alt="image" src="https://github.com/equinor/radix-web-console/assets/702860/585d1dc3-2978-45f9-9900-ea31859fea5e">
Lib's repo has a [registered issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5724) regarding this.
There are a [suggested workaround to catch this error](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5724#issuecomment-1862727673) and [mitigation guideline](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#monitor_window_timeout).

**Comment by emirgens** [comment]
Rare cases. Update this if it occurs again.
Low priority

**Comment by emirgens** [comment]
No additional reports of this. Closing issue
